### PR TITLE
avoid race condition

### LINKED ISSUE #13: Race condition when directory contents change?
I'm running up against what I assume is some sort of race condition:

`
2021-01-31 00:45:39,906 ERROR An uncaught exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 218, in <module>
    start()
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 193, in start
    for event in inotify.read():
  File "/usr/lib/python2.7/site-packages/inotifyrecursive/inotifyrecursive.py", line 149, in read
    moved_from[event.cookie] = info["children"][event.name]
KeyError: 'MOVED_DIR'
`

I suspect MOVED_DIR is being moved while the directory is being traversed.

### PR DESCRIPTION
**Pull request by nferch**
Closes #13

### CODE REVIEW

**Comment by letorbi** [comment]
Thanks for the PR. Have you tested it for possible side-effects, like missed changes in the watched folder or similar?

**Comment by nferch** [comment]
I've been monitoring the debug logs. From what I can tell, the files' eventual destination was added to the index via `synoindex -a`. So it seems to not have any bad side-effects for my use case, I did not try and induce any problems or do any stress testing.

**Comment by letorbi** [comment]
The PR looks good to me, but I'd like to do some testing on my own before I merge it. When I look at my calendar I'd say I can do this in the last week of march.

**Comment by letorbi** [comment]
Sorry for not having merged this PR, yet. I am just too busy. But it is still on my list...

**Pull request merged**
